packages:
    - ./package
    - ./test

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    esbuild: false

catalogs:
    dev:
        "oxlint": 1.70.0
    peer:
        "oxlint": ^1.70.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/*"
    - "@rolldown/*"
    - "rolldown"
    - "@tsdown/*"
    - "tsdown"
