packages:
    - ./package
    - ./test

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    esbuild: false

catalogs:
    dev:
        "oxlint": 1.68.0
    peer:
        "oxlint": ^1.68.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    - "@rolldown/*"
    - "rolldown"
    - "@tsdown/*"
    - "tsdown"
